import { NavLink } from "react-router-dom";
import { phases } from "../config/blueprintSchema";
import { phaseCompletion, overallCompletion } from "../lib/progress";
import { metrics } from "../lib/loadBlueprint";

export default function Sidebar() {
  const overall = overallCompletion();
  const pct = overall.total ? Math.round((overall.done / overall.total) * 100) : 0;

  return (
    <aside className="hidden md:flex w-64 shrink-0 flex-col border-r border-border bg-surface/60 px-4 py-6 sticky top-0 h-screen overflow-y-auto">
      <NavLink to="/" className="mb-1 block">
        <div className="text-sm font-semibold text-white truncate">
          {metrics.project.name || "Your SaaS"}
        </div>
        <div className="text-xs text-slate-500">Blueprint Dashboard</div>
      </NavLink>

      <div className="mt-4 mb-6">
        <div className="flex items-center justify-between text-xs text-slate-400 mb-1.5">
          <span>Overall progress</span>
          <span>{pct}%</span>
        </div>
        <div className="h-1.5 rounded-full bg-surface2 overflow-hidden">
          <div
            className="h-full bg-brand rounded-full transition-all"
            style={{ width: `${pct}%` }}
          />
        </div>
      </div>

      <nav className="flex-1 space-y-1">
        <NavLink
          to="/"
          end
          className={({ isActive }) =>
            `block rounded-lg px-3 py-2 text-sm font-medium transition-colors ${
              isActive ? "bg-brand-dim text-brand" : "text-slate-300 hover:bg-surface2"
            }`
          }
        >
          Overview
        </NavLink>

        <div className="pt-4 pb-1 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500">
          Phases
        </div>

        {phases.map((phase) => {
          const c = phaseCompletion(phase.id);
          return (
            <NavLink
              key={phase.id}
              to={`/phase/${phase.id}`}
              className={({ isActive }) =>
                `flex items-center justify-between gap-2 rounded-lg px-3 py-2 text-sm transition-colors ${
                  isActive ? "bg-surface2 text-white" : "text-slate-300 hover:bg-surface2"
                }`
              }
            >
              <span className="flex items-center gap-2 min-w-0">
                <span
                  className="h-1.5 w-1.5 rounded-full shrink-0"
                  style={{ backgroundColor: phase.color }}
                />
                <span className="truncate">{phase.label}</span>
              </span>
              <span className="text-[11px] text-slate-500 shrink-0">
                {c.done}/{c.total}
              </span>
            </NavLink>
          );
        })}
      </nav>

      <div className="pt-4 mt-4 border-t border-border text-[11px] text-slate-600">
        Generated by PlanMySaaS Skill
      </div>
    </aside>
  );
}
